#--------------------------------------------------------------#
# Copyright 2021 Norsk Datateknikk AS                          #
#--------------------------------------------------------------#
# This file is subject to the terms and conditions defined in  #
# file 'LICENSE', which is part of this source code package.   #
#--------------------------------------------------------------#

[package]
name = "ndsp"
version = "0.1.0"
authors = ["Erik Buer"]
edition = "2018"
description = "A package conaining DSP-related functions."
readme = "README.md"
repository = "https://github.com/norsk-datateknikk/NDSP"
license = "MIT"
license-file = "LICENSE"
keywords = ["dsp", "radio", "audio"]

[lib]
name = "ndsp"
bench = false
test = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#plotters = "^0.3.0"
#itertools = ""
#itertools-num = ""
num-traits = ""
num = ""
num-complex = "0.3" # Ensure this is the same version as used in num-complex
rustfft = ""
impl_ops = ""
