#--------------------------------------------------------------#
# Copyright 2021 Norsk Datateknikk AS                          #
#--------------------------------------------------------------#
# This file is subject to the terms and conditions defined in  #
# file 'LICENSE', which is part of this source code package.   #
#--------------------------------------------------------------#

[package]
name = "ndsp"
version = "0.1.0"
authors = ["Erik Buer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "^0.3.0"
itertools = ""
itertools-num = ""
num-traits = ""
num = ""
num-complex = ""
