#--------------------------------------------------------------#
# Copyright 2021 Norsk Datateknikk AS                          #
#--------------------------------------------------------------#
# This file is subject to the terms and conditions defined in  #
# file 'LICENSE', which is part of this source code package.   #
#--------------------------------------------------------------#

[package]
name = "ndsp"
version = "0.1.0"
authors = ["Erik Buer"]
edition = "2021"
description = "A package conaining DSP-related functions."
readme = "README.md"
repository = "https://github.com/norsk-datateknikk/NDSP"
license-file = "LICENSE"
keywords = ["dsp", "radio", "audio", "no_std"]

[lib]
name = "ndsp"
path  = "src/lib.rs"
bench = false
doc   = true
test  = true
edition    = "2018"
crate-type = ["lib"]

[dependencies]
fixed_trigonometry = "^0.3.0"
fixed = "^1.10.0"

[dependencies.num]
version = "^0.4"
default-features = false

[dev-dependencies]
plotters = "^0.3.1"